default:
  tags:
   - exec-docker 
  image: node:latest
  cache:  # Cache modules in between jobs
    key: $CI_COMMIT_REF_SLUG
    paths:
      - .npm/
  before_script:
    - npm ci --cache .npm --prefer-offline

stages:
  - install
  - test
  - deploy:images

install_dependencies:
  stage: install
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

test:
  stage: test
  script:
    - npm test

.deploy-to-dockerhub:
  stage: deploy:images
  before_script: []
  cache: []
  variables:
    DOCKERHUB_IMAGE_NAME: 'metrics-service'
    DOCKERHUB_TAG: 'latest'
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$EXPLORVIZ_CI_REGISTRY_KANIKO\":{\"auth\":\"$(echo -n ${EXPLORVIZ_DOCKERHUB_USERNAME}:${EXPLORVIZ_DOCKERHUB_PASSWORD} | base64)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context=$CI_PROJECT_DIR --dockerfile=$CI_PROJECT_DIR/Dockerfile --destination=$EXPLORVIZ_DOCKERHUB_ORGA/$DOCKERHUB_IMAGE_NAME:$DOCKERHUB_TAG

deploy-dockerhub-main:
  extends:
    - .deploy-to-dockerhub
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_PIPELINE_SOURCE != "schedule" && $CI_COMMIT_BRANCH == "main"'

deploy-dockerhub-mr:
  variables:
    DOCKERHUB_TAG: $CI_COMMIT_SHORT_SHA
  extends:
    - .deploy-to-dockerhub
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

