version: '3'
services:

  # Metrics-Service
  metric-service:
    hostname: metric-service
    build: .
    ports:
      - "8085:8085"
    networks:
      - explorviz
    depends_on: 
      - influxdb

  # Influx database
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - explorviz


volumes:
  influxdb-data:

networks:
  explorviz:
    name: explorviz
    external: true