version: '3'
services:

  metric-service:
    build: .
    ports:
      - "3000:3000"
    networks:
      - explorviz
    depends_on: 
      - influxdb


  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - explorviz


volumes:
  influxdb-data:

networks:
  explorviz:
    name: explorviz
    external: true